[features]
seeds = false
[programs.devnet]
liquifier = "LQU1Teo79ekWeqz6W8hcbjRRzhSrbarqhfNsgWEDe1g"
one_o_one = "ooou9iMYreTDSFrzEEJYSNHdHDfMaX1MA5D2zQnDQTo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/Users/bhargavveepuri/wallets/solana/solana-wallet_linux/SALThRKa8JFD3XoGbLshzg61kaBHFFCeggDH8ydNEaE.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
