[features]
seeds = false
[programs.devnet]
liquifier = "4gHkd41joA4RyNuFY9UYYUbsBwAgjTomRoZFJjLwd5ht"
one_o_one = "GaTmPSkohwxmaK5THGQv3vms5Ernm4hYBaBDz8VCfmUp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://rpc-devnet.helius.xyz/?api-key=ec0c9707-e412-45e4-9608-5a4cb6141af9"
wallet = "/home/abstracted/ant_labs/wallets/TempUpdateAuthority/TUAXRFzyLeXmG9wPLaMXt66jUagfrWmL9oGq4rMwjAu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
